version: "3.8"

services:
  db:
    image: postgres:16
    container_name: devops_hemtenta_db
    env_file:
      - /etc/devops_hemtenta_env
    ports:
      - "5431:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: devops_hemtenta_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - /etc/devops_hemtenta_env
    depends_on:
      - db
    restart: unless-stopped

    volumes:
      - ./api:/api

volumes:
  db_data_dev:
